- name: configure packages
  hosts: localhost
  become: yes
  tasks:
  - name: configure rpmfusion
    dnf:
      state: present
      name: 
      -  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
      -  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
  
  - name: install packages
    dnf:
      name:
        - vim-enhanced
        - gstreamer-plugins-ugly
        - gstreamer-plugins-bad
        - mplayer
        - dconf-editor
        - ansible
      state: latest
  - name: Disable suspend on lid close 
    lineinfile:
      path: /etc/systemd/logind.conf
      regexp: " {{item}}="
      line: " {{item}}=ignore"
    with_items: 
      - HandleLidSwitch
      - HandleLidSwitchExternalPower
      - HandleLidSwitchDocked
