- hosts: localhost
  become: no
  ignore_errors: true
  tasks:
    - name: set gnome vars
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll", value: "false" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled", value: "true" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "true" }
        - { key: "/org/gnome/desktop/screensaver/lock-enabled", value: "false" }
        - { key: "/org/gnome/setting-daemon/plugins/power/sleep-inactive-ac-timeout", value: "3600" }
        - { key: "/org/gnome/setting-daemon/plugins/power/power-button-action", value: "hibernate" }
        - { key: "/org/gnome/terminal/audible-bell", value: "false" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color", value: "'rgb(0,0,0)'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color", value: "'rgb(0,255,79)'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollback-unlimited", value: "true" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy", value: "'never'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors", value: "false" }
    - name: setup vimrc
      copy:
        dest: ~/.vimrc
        create: true
        content: |
          autocmd FileType yaml setlocal et ts=2 ai sw=2 sts=0
          autocmd filetype python set ts=4 et ai sw=4 sts=4 tw=79
          set background=dark
    - name: setup .bcrc
      blockinfile:
        path: ~/.bcrc
        create: true
        block: |
          scale=2
    - name: push .bcrc into bash
      blockinfile:
        path: ~/.bashrc
        block: |
          export BC_ENV_ARGS=~/.bcrc
    - name: set symlinks
      file:
        dest: /home/judd.obannon/{{ item.key }}
        src: /home/judd.obannon/{{ item.value }}
        state: link
      loop: 
        - { key: "Desktop", value: "desktop" }
        - { key: "Downloads", value: "downloads" }
