- name: configure packages
  hosts: localhost
  become: yes
  tasks:
  - name: configure rpmfusion
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      -  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
      -  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
  
  - name: install packages
    dnf:
      name:
        - vim-enhanced
        - gstreamer-plugins-ugly
        - gstreamer-plugins-bad
        - mplayer
        - dconf-editor
        - ansible
      state: latest
  
