- name: configure packages
  hosts: localhost
  become: yes
  tasks:
  - name: create chrome repo
    copy:
      dest: /etc/yum.repos.d/google-chrome.repo
      content: |
        [google-chrome]
        name=google-chrome
        baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled=1
        gpgcheck=1
        gpgkey=https://dl.google.com/linux/linux_signing_key.pub
      tags: repo
  - name: create brave repo
    copy:
      dest: /etc/yum.repos.d/brave-browser.repo
      content: |
        [brave-browser-rpm-release.s3.brave.com_x86_64_]
        name=brave-browser
        baseurl=https://brave-browser-rpm-release.s3.brave.com/x86_64/
        enabled=1
    tags: repo
  - name: install rpm keys for above
    rpm_key:
      key: "{{ item }}"
      state: present
    loop:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      - https://dl.google.com/linux/linux_signing_key.pub
    tags: repo
  - name: configure rpmfusion
    dnf:
      state: present
      name: 
      -  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
      -  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
    tags: repo
  - name: install packages
    dnf:
      name:
        - vim-enhanced
        - gstreamer-plugins-ugly
        - gstreamer-plugins-bad
        - mplayer
        - dconf-editor
        - ansible
        - xfreerdp
        - python3-requests
        - python3-psutil
        - dnf-automatic
        - rpmdevtools
        - feh
        - google-chrome
        - brave-browser
      state: latest
  - name: update everything
    dnf:
      name: "*"
      state: latest
  - name: Disable suspend on lid close 
    lineinfile:
      path: /etc/systemd/logind.conf
      regexp: " {{item}}="
      line: " {{item}}=ignore"
    with_items: 
      - HandleLidSwitch
      - HandleLidSwitchExternalPower
      - HandleLidSwitchDocked
  - name: Restart system
      shell: nohup bash -c "sleep 2s && shutdown -r now" &
      async: 1
      poll: 0
      ignore_errors: true

