- hosts: localhost
  become: no
  ignore_errors: true
  gather_facts: false
  tasks:
    - name: set gnome vars
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll", value: "false" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled", value: "true" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "true" }
        - { key: "/org/gnome/desktop/screensaver/lock-enabled", value: "false" }
        - { key: "/org/gnome/setting-daemon/plugins/power/sleep-inactive-ac-timeout", value: "3600" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color", value: "'rgb(0,0,0)'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell", value: "false" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color", value: "'rgb(0,255,79)'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollback-unlimited", value: "true" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy", value: "'never'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/bold-is-bright", value: "true" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font", value: "'Source Code Pro Medium 12'" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/user-system-font", value: "false" }
        - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors", value: "false" }
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings", value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']" }
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>t'" }
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'/usr/bin/gnome-terminal'" }
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'terminal'" }
        - { key: "/org/gnome/desktop/vm", value: "['/org/gnome/desktop/vm/keybindings/']" }
        - { key: "/org/gnome/desktop/vm/keybindings/panel-run-dialog", value: "['<Super>r']" }
        - { key: "/org/gnome/desktop/background/color-shading-type", value: "'solid'" }
        - { key: "/org/gnome/desktop/background/picture-options", value: "'wallpaper'" }
        - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:////usr/share/gnome-control-center/pixmaps/noise-texture-light.png'" }
        - { key: "/org/gnome/desktop/background/primary-color", value: "'#000000'" }
        - { key: "/org/gnome/desktop/background/secondary-color", value: "'#000000'" }
        - { key: "/ca/desrt/dconf-editor/show-warning", value: "false" }
        - { key: "/org/gnome/shell/app-switcher/current-workspace-only", value: "true" }
        - { key: "/org/gnome/desktop/interface/enable-animations", value: "false" }
      tags: gnome
    - name: disable gnome hot corner
      command: "/usr/bin/gnome-shell-extension-tool -e gnome-shell-extension-no-topleft-hot-corner"
    - name: setup vimrc
      copy:
        dest: ~/.vimrc
        content: |
          autocmd FileType yaml setlocal et ts=2 ai sw=2 sts=0 cuc
          autocmd filetype python set ts=4 et ai sw=4 sts=4 tw=79
          set background=dark
    - name: setup .bcrc
      blockinfile:
        path: ~/.bcrc
        create: true
        block: |
          scale=2
    - name: push .bcrc into bash
      blockinfile:
        path: ~/.bashrc
        block: |
          export BC_ENV_ARGS=~/.bcrc
          alias sshlp='ssh -i ~/.ssh/id_linux-patching -l linux-patching'
          alias gs='git status -s'
          alias mplayer='mplayer -af scaletempo'
    - name: set symlinks
      file:
        dest: /home/judd.obannon/{{ item.key }}
        src: /home/judd.obannon/{{ item.value }}
        state: link
      loop: 
        - { key: "downloads", value: "Downloads" }
