- hosts: localhost
  become: no
  ignore_errors: true
  tasks:
    - name: set touchpad vars
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll", value: "false" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled", value: "true" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "true" }
        - { key: "/org/gnome/desktop/screensaver/lock-enabled", value: "false" }
        - { key: "/org/gnome/setting-daemon/plugins/power/sleep-inactive-ac-timeout", value: "3600" }
        - { key: "/org/gnome/setting-daemon/plugins/power/power-button-action", value: "hibernate" }
        - { key: "/org/gnome/terminal/audible-bell", value: "false" }
        - { key: "/org/gnome/terminal/background-color", value: "'rgb(0,0,0)'" }
        - { key: "/org/gnome/terminal/foreground-color", value: "'rgb(0,255,0)'" }
        - { key: "/org/gnome/terminal/scrollback-unlimited", value: "true" }
        - { key: "/org/gnome/terminal/scrollbar-policy", value: "'never'" }
        - { key: "/org/gnome/terminal/use-theme-colors", value: "false" }
    - name: setup vimrc
      blockinfile:
        path: ~/.vimrc
        create: true
        block: |
          autocmd FileType yaml setlocal et ts=2 ai sw=2 sts=0
          autocmd filetype python set ts=4 et ai sw=4 sts=4 tw=79
    - name: setup .bcrc
      blockinfile:
        path: ~/.bcrc
        create: true
        block: |
          scale=2
    - name: push .bcrc into bash
      blockinfile:
        path: ~/.bashrc
        block: |
          export BC_ENV_ARGS=~/.bcrc

